# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 15:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
