# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b427487-f808-40dd-b3d3-9a960c070b23'), primary_key=True, serialize=False),
        ),
    ]
