# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20181209_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bed9676c-f585-4a8d-9cb8-43a1941c20bc'), primary_key=True, serialize=False),
        ),
    ]
