# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181209_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('caea5ee4-e8d7-4963-a4f4-c1f80451ccba'), primary_key=True, serialize=False),
        ),
    ]
