# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181209_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9479714-bd33-474f-b4e5-29fd5ab01adc'), primary_key=True, serialize=False),
        ),
    ]
